"""Standard rule-engine skip reasons and final decisions."""

SKIP_HTF_BIAS_CONFLICT = "SKIP_HTF_BIAS_CONFLICT"
SKIP_HTF_BIAS_NEUTRAL = "SKIP_HTF_BIAS_NEUTRAL"

SKIP_NO_ORDER_BLOCK_FOUND = "SKIP_NO_ORDER_BLOCK_FOUND"
SKIP_OB_FULLY_MITIGATED = "SKIP_OB_FULLY_MITIGATED"

SKIP_NO_EMA_DIRECTION = "SKIP_NO_EMA_DIRECTION"
SKIP_PRICE_TOO_CLOSE_TO_EMA = "SKIP_PRICE_TOO_CLOSE_TO_EMA"
SKIP_EMA_FLAT = "SKIP_EMA_FLAT"
SKIP_EMA_CONFLICT = "SKIP_EMA_CONFLICT"
SKIP_RANGING_AROUND_EMA = "SKIP_RANGING_AROUND_EMA"

SKIP_REVERSAL_SETUP = "SKIP_REVERSAL_SETUP"
SKIP_NO_VALID_SWING_LOW = "SKIP_NO_VALID_SWING_LOW"
SKIP_NO_VALID_SWING_HIGH = "SKIP_NO_VALID_SWING_HIGH"
SKIP_LEVEL_TOO_OLD = "SKIP_LEVEL_TOO_OLD"
SKIP_LEVEL_ALREADY_SWEPT = "SKIP_LEVEL_ALREADY_SWEPT"
SKIP_STRUCTURE_NOT_CLEAN = "SKIP_STRUCTURE_NOT_CLEAN"

SKIP_NOT_INSIDE_IMBALANCE = "SKIP_NOT_INSIDE_IMBALANCE"

SKIP_NO_SWEEP = "SKIP_NO_SWEEP"
SKIP_SWEEP_CLOSED_BEYOND_LEVEL = "SKIP_SWEEP_CLOSED_BEYOND_LEVEL"
SKIP_WRONG_CANDLE_COLOUR = "SKIP_WRONG_CANDLE_COLOUR"
SKIP_SWEEP_TOO_SMALL = "SKIP_SWEEP_TOO_SMALL"
SKIP_SWEEP_TOO_DEEP = "SKIP_SWEEP_TOO_DEEP"
SKIP_WICK_TOO_SMALL = "SKIP_WICK_TOO_SMALL"
SKIP_CLOSE_POSITION_WEAK = "SKIP_CLOSE_POSITION_WEAK"

SKIP_RECTANGLE_TOO_SMALL = "SKIP_RECTANGLE_TOO_SMALL"
SKIP_RECTANGLE_TOO_LARGE = "SKIP_RECTANGLE_TOO_LARGE"

SKIP_AI_REJECTED = "SKIP_AI_REJECTED"
SKIP_AI_TIMEOUT = "SKIP_AI_TIMEOUT"
SKIP_AI_INVALID_RESPONSE = "SKIP_AI_INVALID_RESPONSE"

SKIP_M1_FLIP_TIMEOUT = "SKIP_M1_FLIP_TIMEOUT"
SKIP_M1_CLOSE_NOT_OUTSIDE_RECTANGLE = "SKIP_M1_CLOSE_NOT_OUTSIDE_RECTANGLE"

SKIP_SPREAD_TOO_HIGH = "SKIP_SPREAD_TOO_HIGH"
SKIP_MARKET_CLOSED = "SKIP_MARKET_CLOSED"
SKIP_SYMBOL_NOT_TRADABLE = "SKIP_SYMBOL_NOT_TRADABLE"
SKIP_MT5_DISCONNECTED = "SKIP_MT5_DISCONNECTED"
SKIP_EXISTING_POSITION = "SKIP_EXISTING_POSITION"

SKIP_DAILY_LOSS_LIMIT = "SKIP_DAILY_LOSS_LIMIT"
SKIP_MAX_OPEN_POSITIONS = "SKIP_MAX_OPEN_POSITIONS"
SKIP_MAX_SYMBOL_TRADES_REACHED = "SKIP_MAX_SYMBOL_TRADES_REACHED"
SKIP_LOT_SIZE_TOO_SMALL = "SKIP_LOT_SIZE_TOO_SMALL"
SKIP_LOT_SIZE_TOO_LARGE = "SKIP_LOT_SIZE_TOO_LARGE"
SKIP_RR_BELOW_MINIMUM = "SKIP_RR_BELOW_MINIMUM"

NO_SETUP = "NO_SETUP"
SETUP_DETECTED_WAITING_FOR_AI = "SETUP_DETECTED_WAITING_FOR_AI"
SETUP_REJECTED_BY_AI = "SETUP_REJECTED_BY_AI"
RECTANGLE_ACTIVE_WAITING_FOR_M1 = "RECTANGLE_ACTIVE_WAITING_FOR_M1"
ENTRY_SIGNAL_READY = "ENTRY_SIGNAL_READY"
TRADE_BLOCKED_BY_RISK = "TRADE_BLOCKED_BY_RISK"
ORDER_READY = "ORDER_READY"
